### ISSUE TITLE
wrong demo link

### ISSUE THREAD

**Issue by abulka** [Ju99ernaut/grapesjs-script-editor#1]
Great plugin!  

The demo link on https://github.com/Ju99ernaut/grapesjs-script-editor opens https://codepen.io/ju99ernaut/pen/NWNEWpV which is the wrong demo - its a demo of grapesjs-rulers.

**Comment by Ju99ernaut** [comment]
Some extensions share the same demo link, to demo the script editor select a component then click on this icon on the toolbar 
![Screenshot_20210213-084055_Chrome](https://user-images.githubusercontent.com/48953676/107844206-3128fd00-6dda-11eb-82b9-61ff344717b3.jpg)
