### ISSUE TITLE
Script characters are not decoded when loaded.

### ISSUE THREAD

**Issue by cederron** [Ju99ernaut/grapesjs-script-editor#5]
Hi, I'm using grapes 0.18.41 with grapesjs-script-editor and grapesjs-template-manager.
When loading data from backend containing grapesjs-script-editor scripts, characters are not decoded. For example symbol '&lt' is not decoded to '<' so the script errors out. This only happens with grapesjs-script-editor scripts. Scripts written in the component definition are loaded just fine for example.
Only found one similar issue commented and the guy was told to go checkout StorageManager setup, I don't see how this helps, besides, at least in my project, storage seems well configured as everythings saves/loads fine except grapesjs-script-editor scripts.

Any clue what can be happening and how to fix it ?
Thanks.

**Comment by Ju99ernaut** [comment]
Hi, unfortunately I don't know what could be causing this issue.

**Comment by cederron** [comment]
I did a quick hack , adding this code to grapesjs pagemanager  in function _onPageChange

`var txt = document.createElement("textarea");
      txt.innerHTML = mainComp.attributes.script;
      mainComp.attributes.script = txt.value;`

Now it works.
